import zmq
import time

# 1. Correct import path for your project structure
try:
    from src.core.network_config import ZMQ_PORT_PLC_CMD
    COMMAND_PORT = ZMQ_PORT_PLC_CMD
except ImportError as e:
    print(f"ERROR: Could not import network_config. Make sure you are running from the project root. ({e})")
    exit()

# 2. Translate 0.0.0.0 to localhost so the connect() function works on Windows
COMMAND_PORT = COMMAND_PORT.replace("0.0.0.0", "127.0.0.1")

# Ensure it has the tcp:// prefix
if not COMMAND_PORT.startswith("tcp://"):
    COMMAND_PORT = f"tcp://{COMMAND_PORT}"
def request_gate_valve_open():
    context = zmq.Context()
    socket = context.socket(zmq.PUB)

    print(f"Connecting to PLC Data Broker at {COMMAND_PORT}...")
    socket.connect(COMMAND_PORT)

    # CRITICAL: Allow the ZMQ PUB/SUB handshake to complete
    time.sleep(0.2)

    # The exact tag generated by your build_registry.py script
    payload = {
        "tag": "ion_beam.source.chamber.cmd_open_gv",
        "value": False,
        "ts": time.time()
    }

    print(f"Sending command to PLC Broker: {payload}")
    socket.send_json(payload)

    time.sleep(0.1)
    socket.close()
    context.term()
    print("Command transmitted. Gate valve should close!")

if __name__ == "__main__":
    request_gate_valve_open()